import React, { useEffect, useMemo, useRef, useState } from "react";

type View = "hoy" | "plan" | "compra" | "entreno" | "progreso" | "ajustes";
type Meal = { id:string; type:string; name:string; kcal:number; protein:number; prep:string; ingredients:{name:string;qty:number;unit:string;price:number}[] };
type DayMeal = { mealId:string; servings:number; quantities?:Record<string,number>; outside:boolean; label?:string; kcal?:number; protein?:number; carbs?:number; fat?:number };
type Exercise = { name:string; sets:number; reps:string; unit:string; defaultWeight:number; instructions:string };
type Workout = { id:string; name:string; kind:"pump"|"strength"|"rest"; duration:number; exercises:Exercise[] };
type Session = { id:string; date:string; workoutId:string; entries:Record<string,{weight:string;reps:string}>; completed:boolean };
type Measurement = { id:string; date:string; weight:number; fat?:number; muscle?:number };
type Settings = { name:string; weeklyBudget:number; monthlyBudget:number; calorieGoal:number; proteinGoal:number; carbGoal:number; fatGoal:number; restSeconds:number; dark:boolean };
type AppData = { mealChoices:Record<string,string>; dayMeals:Record<string,Record<string,DayMeal>>; freeMeals:string[]; unavailable:string[]; scheduleOverrides:Record<string,string>; shoppingChecked:string[]; extraItems:string[]; sessions:Session[]; measurements:Measurement[]; settings:Settings; streakDates:string[] };

const mealOptions:Record<string,Meal[]> = {
 breakfast:[
  {id:"breakfast-toast",type:"Desayuno",name:"Tostada con tomate, cottage y pavo",kcal:365,protein:27,prep:"Tuesta el pan, añade tomate, cottage y pavo. Acompaña con café y leche.",ingredients:[{name:"Pan integral",qty:70,unit:"g",price:.32},{name:"Tomate",qty:100,unit:"g",price:.28},{name:"Queso cottage",qty:80,unit:"g",price:.72},{name:"Pavo loncheado",qty:50,unit:"g",price:.85},{name:"Leche semidesnatada",qty:150,unit:"ml",price:.16},{name:"Café",qty:1,unit:"taza",price:.18}]},
  {id:"breakfast-yogurt",type:"Desayuno",name:"Bol de yogur, avena y fruta",kcal:390,protein:25,prep:"Mezcla el yogur con avena y fruta. Añade canela al gusto.",ingredients:[{name:"Yogur griego natural",qty:250,unit:"g",price:1.1},{name:"Copos de avena",qty:45,unit:"g",price:.12},{name:"Plátano",qty:1,unit:"ud",price:.32},{name:"Almendras",qty:10,unit:"g",price:.2}]}
 ],
 lunch:[
  {id:"lunch-chicken",type:"Comida",name:"Pollo mediterráneo con arroz",kcal:585,protein:45,prep:"Cuece el arroz. Saltea pollo y verduras con el aceite medido y mezcla.",ingredients:[{name:"Pechuga de pollo",qty:150,unit:"g",price:1.35},{name:"Arroz",qty:70,unit:"g",price:.16},{name:"Calabacín",qty:120,unit:"g",price:.24},{name:"Pimiento rojo",qty:80,unit:"g",price:.25},{name:"Aceite de oliva",qty:10,unit:"ml",price:.09}]},
  {id:"lunch-lentils",type:"Comida",name:"Ensalada templada de lentejas y huevo",kcal:560,protein:32,prep:"Mezcla las lentejas escurridas con verduras salteadas y huevo cocido.",ingredients:[{name:"Lentejas cocidas",qty:250,unit:"g",price:.85},{name:"Huevos",qty:2,unit:"ud",price:.5},{name:"Tomate",qty:120,unit:"g",price:.34},{name:"Espinacas",qty:80,unit:"g",price:.6},{name:"Aceite de oliva",qty:10,unit:"ml",price:.09}]},
  {id:"lunch-salmon",type:"Comida",name:"Salmón con patata y ensalada",kcal:610,protein:39,prep:"Hornea el salmón y la patata. Sirve con ensalada y limón.",ingredients:[{name:"Salmón",qty:150,unit:"g",price:2.8},{name:"Patatas",qty:250,unit:"g",price:.38},{name:"Mezcla de ensalada",qty:100,unit:"g",price:.75},{name:"Aceite de oliva",qty:8,unit:"ml",price:.08}]}
 ],
 dinner:[
  {id:"dinner-omelette",type:"Cena",name:"Crema de calabacín y tortilla",kcal:430,protein:28,prep:"Cuece y tritura la crema. Prepara la tortilla con huevos y claras.",ingredients:[{name:"Calabacín",qty:300,unit:"g",price:.6},{name:"Patatas",qty:100,unit:"g",price:.15},{name:"Cebolla",qty:60,unit:"g",price:.1},{name:"Huevos",qty:2,unit:"ud",price:.5},{name:"Claras",qty:100,unit:"ml",price:.55},{name:"Aceite de oliva",qty:5,unit:"ml",price:.05}]},
  {id:"dinner-wrap",type:"Cena",name:"Wrap integral de pollo y verduras",kcal:455,protein:35,prep:"Saltea el pollo y las verduras. Rellena y tuesta el wrap.",ingredients:[{name:"Tortilla integral",qty:1,unit:"ud",price:.35},{name:"Pechuga de pollo",qty:110,unit:"g",price:.99},{name:"Pimiento rojo",qty:60,unit:"g",price:.19},{name:"Cebolla",qty:40,unit:"g",price:.07},{name:"Yogur natural",qty:50,unit:"g",price:.18}]},
  {id:"dinner-hake",type:"Cena",name:"Merluza con verduras al horno",kcal:420,protein:38,prep:"Hornea la merluza y las verduras 20 minutos con limón y especias.",ingredients:[{name:"Merluza",qty:180,unit:"g",price:2.1},{name:"Calabacín",qty:180,unit:"g",price:.36},{name:"Tomate",qty:120,unit:"g",price:.34},{name:"Patatas",qty:150,unit:"g",price:.23},{name:"Aceite de oliva",qty:8,unit:"ml",price:.08}]}
 ]
};
mealOptions.snack=[
 {id:"snack-yogurt",type:"Merienda",name:"Yogur con fruta",kcal:210,protein:15,prep:"Sirve el yogur con la fruta troceada.",ingredients:[{name:"Yogur griego natural",qty:150,unit:"g",price:.66},{name:"Plátano",qty:1,unit:"ud",price:.32}]},
 {id:"snack-toast",type:"Merienda",name:"Tostada de cottage y pavo",kcal:240,protein:20,prep:"Tuesta el pan y añade cottage y pavo.",ingredients:[{name:"Pan integral",qty:40,unit:"g",price:.18},{name:"Queso cottage",qty:50,unit:"g",price:.45},{name:"Pavo loncheado",qty:40,unit:"g",price:.68}]}
];

const strengthA:Exercise[]=[
 {name:"Sentadilla en multipower",sets:3,reps:"8–10",unit:"kg",defaultWeight:30,instructions:"Pies algo adelantados, rodillas en línea con los pies y espalda neutra. Baja sin dolor y empuja el suelo."},
 {name:"Peso muerto rumano",sets:3,reps:"10",unit:"kg",defaultWeight:22,instructions:"Lleva la cadera atrás con rodillas suaves. Mantén la carga cerca del cuerpo y la espalda neutra."},
 {name:"Remo sentado",sets:3,reps:"10–12",unit:"kg",defaultWeight:25,instructions:"Pecho estable, hombros lejos de las orejas. Lleva los codos atrás sin balancearte."},
 {name:"Press de pecho",sets:3,reps:"8–10",unit:"kg",defaultWeight:17.5,instructions:"Escápulas apoyadas y muñecas neutras. Baja con control y no bloquees los codos."},
 {name:"Hip thrust",sets:3,reps:"10",unit:"kg",defaultWeight:40,instructions:"Barbilla recogida, pelvis neutra y pausa arriba apretando glúteos sin arquear la espalda."}
];
const strengthB:Exercise[]=[
 {name:"Prensa inclinada",sets:3,reps:"10–12",unit:"kg",defaultWeight:55,instructions:"Apoya toda la espalda y coloca los pies a una anchura cómoda. No bloquees las rodillas."},
 {name:"Jalón al pecho",sets:3,reps:"10–12",unit:"kg",defaultWeight:25,instructions:"Baja la barra hacia la parte alta del pecho llevando los codos abajo, sin tirar con impulso."},
 {name:"Zancada atrás",sets:3,reps:"8 por lado",unit:"kg",defaultWeight:8,instructions:"Da un paso atrás y mantén estable la rodilla delantera. Empuja con el pie delantero."},
 {name:"Press de hombro",sets:3,reps:"10",unit:"kg",defaultWeight:10,instructions:"Costillas controladas y hombros bajos. Empuja arriba sin arquear la zona lumbar."},
 {name:"Plancha",sets:3,reps:"30–45 s",unit:"s",defaultWeight:30,instructions:"Contrae abdomen y glúteos manteniendo una línea recta. Para si pierdes la postura."}
];
const workouts:Record<string,Workout>={pump:{id:"pump",name:"BodyPump",kind:"pump",duration:60,exercises:[]},strengthA:{id:"strengthA",name:"Fuerza A",kind:"strength",duration:50,exercises:strengthA},strengthB:{id:"strengthB",name:"Fuerza B",kind:"strength",duration:45,exercises:strengthB},rest:{id:"rest",name:"Descanso activo",kind:"rest",duration:20,exercises:[]}};
const schedule=["pump","rest","strengthA","rest","pump","strengthB","rest"];
const slots=["breakfast","lunch","snack","dinner"];
const macroTable:Record<string,{carbs:number;fat:number}>={"breakfast-toast":{carbs:42,fat:10},"breakfast-yogurt":{carbs:48,fat:11},"lunch-chicken":{carbs:66,fat:15},"lunch-lentils":{carbs:63,fat:18},"lunch-salmon":{carbs:45,fat:27},"dinner-omelette":{carbs:34,fat:18},"dinner-wrap":{carbs:44,fat:16},"dinner-hake":{carbs:36,fat:13},"snack-yogurt":{carbs:27,fat:5},"snack-toast":{carbs:24,fat:7}};
const defaults:AppData={mealChoices:{breakfast:"breakfast-toast",lunch:"lunch-chicken",snack:"snack-yogurt",dinner:"dinner-omelette"},dayMeals:{},freeMeals:[],unavailable:[],scheduleOverrides:{},shoppingChecked:[],extraItems:[],sessions:[],measurements:[],settings:{name:"",weeklyBudget:40,monthlyBudget:100,calorieGoal:1650,proteinGoal:105,carbGoal:190,fatGoal:55,restSeconds:90,dark:false},streakDates:[]};
const iso=(d:Date)=>d.toISOString().slice(0,10);
const localISO=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return iso(x)};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const money=(n:number)=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"});
function load():AppData {try{const raw=JSON.parse(localStorage.getItem("equilibra-v2")||"null");return raw?{...defaults,...raw,settings:{...defaults.settings,...raw.settings}}:defaults}catch{return defaults}}
function entryFor(data:AppData,date:string,slot:string):DayMeal{return data.dayMeals[date]?.[slot]||{mealId:data.mealChoices[slot]||mealOptions[slot][0].id,servings:1,outside:false}}
function mealById(id:string){return Object.values(mealOptions).flat().find(m=>m.id===id)!}
function portion(entry:DayMeal,meal:Meal){if(!entry.quantities)return entry.servings;const ratios=meal.ingredients.map(x=>(entry.quantities?.[x.name]??x.qty*entry.servings)/x.qty);return ratios.reduce((a,b)=>a+b,0)/ratios.length}
function macros(entry:DayMeal){if(entry.outside)return{kcal:entry.kcal||0,protein:entry.protein||0,carbs:entry.carbs||0,fat:entry.fat||0};const m=mealById(entry.mealId),factor=portion(entry,m);const extra=macroTable[m.id]||{carbs:0,fat:0};return{kcal:Math.round(m.kcal*factor),protein:Math.round(m.protein*factor),carbs:Math.round(extra.carbs*factor),fat:Math.round(extra.fat*factor)}}
function daySummary(data:AppData,date:string){return slots.map(s=>macros(entryFor(data,date,s))).reduce((a,m)=>({kcal:a.kcal+m.kcal,protein:a.protein+m.protein,carbs:a.carbs+m.carbs,fat:a.fat+m.fat}),{kcal:0,protein:0,carbs:0,fat:0})}

const Icon=({name}:{name:string})=>{const p:Record<string,string>={hoy:"M3 11.5 12 4l9 7.5M5.5 10v10h13V10M9 20v-6h6v6",plan:"M6 3v3m12-3v3M4 8h16v12H4z",compra:"M4 6h16l-2 14H6L4 6z",entreno:"M3 9v6m3-8v10m3-6h6m0-4v10m3-8v6",progreso:"M4 18l5-5 4 3 7-9m-5 0h5v5",ajustes:"M12 8a4 4 0 100 8 4 4 0 000-8zm0-5v2m0 14v2M3 12h2m14 0h2"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={p[name]}/></svg>};

export default function App(){
 const [data,setData]=useState<AppData>(load); const [view,setView]=useState<View>("hoy"); const [editing,setEditing]=useState<{date:string;slot:string}|null>(null); const [toast,setToast]=useState("");
 useEffect(()=>{localStorage.setItem("equilibra-v2",JSON.stringify(data));document.documentElement.dataset.theme=data.settings.dark?"dark":"light"},[data]);
 const update=(patch:Partial<AppData>)=>setData(d=>({...d,...patch})); const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2200)};
 const now=new Date(); const hour=now.getHours(); const greeting=hour<13?"Buenos días":hour<20?"Buenas tardes":"Buenas noches";
 const dateText=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long"}).format(now);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="sprig">⌁</span>Equilibra</div><nav>{(["hoy","plan","compra","entreno","progreso","ajustes"] as View[]).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?"active":""}><Icon name={v}/><span>{v[0].toUpperCase()+v.slice(1)}</span></button>)}</nav><div className="side-note"><b>Este mes</b><span>{data.sessions.filter(s=>s.completed&&s.date.slice(0,7)===localISO().slice(0,7)).length} entrenamientos completados</span></div></aside>
  <main className="content"><header><div><p>{greeting}{data.settings.name?`, ${data.settings.name}`:""}</p><span>{dateText[0].toUpperCase()+dateText.slice(1)}</span></div><button className="avatar" onClick={()=>setView("ajustes")} aria-label="Abrir ajustes">{data.settings.name.slice(0,2).toUpperCase()||"EQ"}</button></header>
   {view==="hoy"&&<Today data={data} update={update} edit={(slot)=>setEditing({date:localISO(),slot})} goWorkout={()=>setView("entreno")}/>}
   {view==="plan"&&<Plan data={data} update={update} edit={(date,slot)=>setEditing({date,slot})}/>}
   {view==="compra"&&<Shopping data={data} update={update}/>}
   {view==="entreno"&&<Training data={data} update={update} notify={notify}/>}
   {view==="progreso"&&<Progress data={data} update={update}/>}
   {view==="ajustes"&&<SettingsPage data={data} update={update} notify={notify}/>}
  </main>{editing&&<DayMealEditor date={editing.date} slot={editing.slot} data={data} update={update} close={()=>setEditing(null)}/>} {toast&&<div className="toast" role="status">{toast}</div>}
 </div>
}

function Today({data,update,edit,goWorkout}:{data:AppData;update:(p:Partial<AppData>)=>void;edit:(slot:string)=>void;goWorkout:()=>void}){
 const today=localISO(),dow=(new Date().getDay()+6)%7;const week=getWeek();const resolved=resolvedWorkouts(data,week);const workout=workouts[resolved[dow]];const done=data.sessions.some(s=>s.date===today&&s.completed);const total=daySummary(data,today);const closed=data.streakDates.includes(today);
 return <section className="page"><div className="title-row"><div><small>HOY</small><h1>Tu día, en equilibrio</h1><p>Registra lo que realmente comes, también cuando sales fuera.</p></div><button className={closed?"secondary":"primary"} onClick={()=>update({streakDates:closed?data.streakDates.filter(x=>x!==today):[...new Set([...data.streakDates,today])]})}>{closed?"Reabrir día":"Cerrar el día"}</button></div><div className="macro-dashboard"><Macro label="Calorías" value={total.kcal} goal={data.settings.calorieGoal} unit="kcal"/><Macro label="Proteína" value={total.protein} goal={data.settings.proteinGoal} unit="g"/><Macro label="Carbohidratos" value={total.carbs} goal={data.settings.carbGoal} unit="g"/><Macro label="Grasas" value={total.fat} goal={data.settings.fatGoal} unit="g"/></div><div className="today-grid"><div className="meal-stack"><div className="section-head"><h2>Diario de comidas</h2><span>Pulsa para editar cantidades</span></div>{slots.map((slot,i)=>{const entry=entryFor(data,today,slot),m=mealById(entry.mealId),mc=macros(entry);return <button className={`meal-card diary ${entry.outside?"outside":""}`} key={slot} onClick={()=>edit(slot)}><div className={`meal-art art-${i%3}`}>{["☕","◒","◐","♨"][i]}</div><div className="meal-copy"><small>{m.type}</small><h3>{entry.outside?(entry.label||`${m.type} fuera`):m.name}</h3><span>{entry.outside?"Estimación editable · no entra en la compra":`${entry.servings} ración · cantidades × ${entry.servings}`}</span></div><div className="meal-macros"><b>{mc.kcal} kcal</b><span>P {mc.protein} · C {mc.carbs} · G {mc.fat}</span></div></button>})}</div><div className="right-col"><article className="workout-card"><div><small>ENTRENAMIENTO DE HOY</small><h2>{workout.name}</h2><p>{workout.duration} min · {done?"Completado":"Pendiente"}</p><button onClick={goWorkout}>{done?"Ver historial":"Abrir entrenamiento"} →</button></div><div className="barbell">●━●</div></article><article className="tip"><span>Balance flexible</span><p>Comer fuera no equivale a no comer. Añade una estimación de sus macros y Equilibra la contará en el día, pero retirará esos ingredientes de la compra.</p></article></div></div></section>
}
function Macro({label,value,goal,unit}:{label:string;value:number;goal:number;unit:string}){const pct=Math.min(100,value/goal*100);return <article className="macro-card"><small>{label}</small><b>{value} <i>{unit}</i></b><span>de {goal} {unit}</span><div><i style={{width:`${pct}%`}}/></div></article>}
function Metric({label,value,total,pct}:{label:string;value:string;total:string;pct:number}){return <article className="metric"><small>{label}</small><div className="ring" style={{"--pct":`${Math.min(100,pct)*3.6}deg`} as React.CSSProperties}><span>{value}<i>/ {total}</i></span></div></article>}
function getWeek(offset=0){const d=new Date();const diff=(d.getDay()+6)%7;d.setDate(d.getDate()-diff+offset*7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x})}
function resolvedWorkouts(data:AppData,days:Date[]){const ids=days.map((d,i)=>data.scheduleOverrides[localISO(d)]||schedule[i]);days.forEach((d,i)=>{const key=localISO(d);if(!data.unavailable.includes(key))return;const displaced=ids[i];ids[i]="rest";if(displaced==="rest")return;for(let j=i+1;j<ids.length;j++){const candidate=localISO(days[j]);if(!data.unavailable.includes(candidate)&&ids[j]==="rest"&&ids[j-1]==="rest"&&(j===ids.length-1||ids[j+1]==="rest")){ids[j]=displaced;break}}});return ids}

function Plan({data,update,edit}:{data:AppData;update:(p:Partial<AppData>)=>void;edit:(date:string,slot:string)=>void}){
 const [weekOffset,setWeekOffset]=useState(0);const days=getWeek(weekOffset);const resolved=resolvedWorkouts(data,days);
 return <section className="page wide"><div className="title-row"><div><small>PLAN SEMANAL</small><h1>Comidas y entrenamientos</h1><p>Planifica la semana completa antes de hacer la compra.</p></div><div className="week-nav"><button onClick={()=>setWeekOffset(x=>x-1)}>←</button><button onClick={()=>setWeekOffset(0)}>Semana actual</button><button onClick={()=>setWeekOffset(x=>x+1)}>→</button></div></div><div className="week-planner">{days.map((d,i)=>{const key=localISO(d),blocked=data.unavailable.includes(key),workout=workouts[resolved[i]],sum=daySummary(data,key);return <article className={`planner-day ${key===localISO()?"today":""}`} key={key}><header><div><b>{new Intl.DateTimeFormat("es-ES",{weekday:"long"}).format(d)}</b><span>{d.getDate()}</span></div><small>{sum.kcal} kcal · {sum.protein} g P</small></header><div className="planner-meals">{slots.map(slot=>{const e=entryFor(data,key,slot),m=mealById(e.mealId);return <button key={slot} className={e.outside?"outside":""} onClick={()=>edit(key,slot)}><small>{m.type}</small><b>{e.outside?(e.label||"Fuera"):m.name}</b><span>{e.outside?"🍴 Fuera":`${e.servings} ración`}</span></button>})}</div><div className="planner-workout"><small>ENTRENAMIENTO</small><select value={data.scheduleOverrides[key]||schedule[i]} disabled={blocked} onChange={e=>update({scheduleOverrides:{...data.scheduleOverrides,[key]:e.target.value}})}><option value="pump">BodyPump</option><option value="strengthA">Fuerza A</option><option value="strengthB">Fuerza B</option><option value="rest">Descanso activo</option></select>{workout.id!==data.scheduleOverrides[key]&&blocked&&<span>Reubicado automáticamente</span>}<label><input type="checkbox" checked={blocked} onChange={()=>update({unavailable:blocked?data.unavailable.filter(x=>x!==key):[...data.unavailable,key]})}/> No puedo entrenar</label></div></article>})}</div><div className="replan"><b>Reorganización activa</b><span>Si bloqueas un entrenamiento, Equilibra intenta colocarlo en el siguiente descanso compatible, evitando sesiones intensas consecutivas. Siempre puedes ajustar el resultado manualmente.</span></div></section>
}
function Shopping({data,update}:{data:AppData;update:(p:Partial<AppData>)=>void}){
 const [extra,setExtra]=useState("");const days=getWeek();const items=useMemo(()=>{const map=new Map<string,{qty:number;unit:string;price:number}>();days.forEach(d=>slots.forEach(slot=>{const e=entryFor(data,localISO(d),slot);if(e.outside)return;const m=mealById(e.mealId);m.ingredients.forEach(x=>{const qty=e.quantities?.[x.name]??x.qty*e.servings,ratio=qty/x.qty,old=map.get(x.name);map.set(x.name,{qty:(old?.qty||0)+qty,unit:x.unit,price:(old?.price||0)+x.price*ratio})})}));return [...map].map(([name,x])=>({name,...x}))},[data.dayMeals,data.mealChoices]);const total=items.reduce((n,x)=>n+x.price,0);const outside=days.flatMap(d=>slots.map(s=>entryFor(data,localISO(d),s))).filter(e=>e.outside).length;
 const toggle=(name:string)=>update({shoppingChecked:data.shoppingChecked.includes(name)?data.shoppingChecked.filter(x=>x!==name):[...data.shoppingChecked,name]});
 return <section className="page"><div className="title-row"><div><small>COMPRA SEMANAL</small><h1>La compra de esta semana</h1><p>Calculada con las raciones de los siete días; excluye {outside} comidas fuera.</p></div><div className="budget-pill"><b>{money(total)}</b><span>de {money(data.settings.weeklyBudget)}</span></div></div>{total>data.settings.weeklyBudget&&<div className="warning"><b>Presupuesto superado</b><span>Reduce alguna ración, cambia recetas o ajusta el límite.</span></div>}<div className="shopping-toolbar"><button onClick={()=>update({shoppingChecked:items.map(x=>x.name)})}>Marcar todo</button><button onClick={()=>update({shoppingChecked:[]})}>Reiniciar</button><label><input type="text" value={extra} placeholder="Añadir producto" onChange={e=>setExtra(e.target.value)}/><button onClick={()=>{if(extra.trim()){update({extraItems:[...data.extraItems,extra.trim()]});setExtra("")}}}>Añadir</button></label></div><div className="shopping-grid dynamic"><article><h2>Menú semanal</h2>{items.map(x=><label key={x.name}><input type="checkbox" checked={data.shoppingChecked.includes(x.name)} onChange={()=>toggle(x.name)}/><span>{x.name} · {x.qty<10?x.qty.toFixed(1):x.qty.toFixed(0)} {x.unit}</span><em>{money(x.price)}</em></label>)}</article><article><h2>Extras</h2>{data.extraItems.length===0&&<p className="empty">No has añadido extras.</p>}{data.extraItems.map(x=><label key={x}><input type="checkbox" checked={data.shoppingChecked.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span><button className="remove" onClick={()=>update({extraItems:data.extraItems.filter(y=>y!==x)})}>×</button></label>)}</article></div></section>
}

function DayMealEditor({date,slot,data,update,close}:{date:string;slot:string;data:AppData;update:(p:Partial<AppData>)=>void;close:()=>void}){const original=entryFor(data,date,slot);const [entry,setEntry]=useState<DayMeal>({...original});const meal=mealById(entry.mealId);const save=()=>{update({dayMeals:{...data.dayMeals,[date]:{...(data.dayMeals[date]||{}),[slot]:entry}}});close()};return <div className="overlay" onMouseDown={close}><div className="modal meal-editor" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><small>{new Date(`${date}T12:00`).toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"long"})}</small><h2>{meal.type}</h2><div className="mode-tabs"><button className={!entry.outside?"active":""} onClick={()=>setEntry({...entry,outside:false})}>Comida del plan</button><button className={entry.outside?"active":""} onClick={()=>setEntry({...entry,outside:true,kcal:entry.kcal||meal.kcal,protein:entry.protein||meal.protein,carbs:entry.carbs||macroTable[meal.id].carbs,fat:entry.fat||macroTable[meal.id].fat})}>Como fuera</button></div>{!entry.outside?<><label className="field">Receta<select value={entry.mealId} onChange={e=>setEntry({...entry,mealId:e.target.value,quantities:undefined})}>{mealOptions[slot].map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field">Cantidad general / raciones<input type="number" min="0.25" max="4" step="0.25" value={entry.servings} onChange={e=>setEntry({...entry,servings:Number(e.target.value),quantities:undefined})}/></label><div className="ingredient-editor"><h3>Cantidades que vas a comer</h3>{meal.ingredients.map(x=><label key={x.name}><span>{x.name}</span><div><input type="number" min="0" step={x.unit==="ud"?1:5} value={entry.quantities?.[x.name]??Math.round(x.qty*entry.servings*100)/100} onChange={e=>setEntry({...entry,quantities:{...Object.fromEntries(meal.ingredients.map(y=>[y.name,entry.quantities?.[y.name]??y.qty*entry.servings])),[x.name]:Number(e.target.value)}})}/><b>{x.unit}</b></div></label>)}</div></>:<><label className="field">Descripción<input value={entry.label||""} placeholder="Ej. cena italiana" onChange={e=>setEntry({...entry,label:e.target.value})}/></label><p className="muted">Introduce una estimación. Se contará en tus macros, pero no añadirá ingredientes a la compra.</p><div className="macro-inputs">{(["kcal","protein","carbs","fat"] as const).map(k=><label key={k}>{({kcal:"Kcal",protein:"Proteína",carbs:"Carbohidratos",fat:"Grasas"})[k]}<input type="number" min="0" value={entry[k]||0} onChange={e=>setEntry({...entry,[k]:Number(e.target.value)})}/></label>)}</div></>}<div className="macro-preview">{Object.entries(macros(entry)).map(([k,v])=><span key={k}><b>{v}</b> {k}</span>)}</div><button className="primary full" onClick={save}>Guardar en este día</button></div></div>}

function Training({data,update,notify}:{data:AppData;update:(p:Partial<AppData>)=>void;notify:(s:string)=>void}){
 const [workoutId,setWorkoutId]=useState("strengthA");const workout=workouts[workoutId];const last=[...data.sessions].reverse().find(s=>s.workoutId===workoutId&&s.completed);const [entries,setEntries]=useState<Record<string,{weight:string;reps:string}>>({});const [info,setInfo]=useState<Exercise|null>(null);
 useEffect(()=>setEntries(Object.fromEntries(workout.exercises.map(e=>[e.name,{weight:last?.entries[e.name]?.weight||String(e.defaultWeight),reps:last?.entries[e.name]?.reps||e.reps}]))),[workoutId]);
 const save=()=>{const session:Session={id:uid(),date:localISO(),workoutId,entries,completed:true};const dates=[...new Set([...data.streakDates,localISO()])];update({sessions:[...data.sessions,session],streakDates:dates});notify("Sesión guardada correctamente")};
 return <section className="page"><div className="title-row"><div><small>ENTRENAMIENTO</small><h1>{workout.name}</h1><p>{workout.duration} minutos · tu última sesión siempre visible.</p></div><div className="workout-actions"><select value={workoutId} onChange={e=>setWorkoutId(e.target.value)}><option value="strengthA">Fuerza A</option><option value="strengthB">Fuerza B</option></select><button className="primary" onClick={save}>Finalizar y guardar</button></div></div><div className="workout-layout"><article className="exercise-list"><div className="table-head"><span>Ejercicio</span><span>Series × repeticiones</span><span>Peso de hoy</span></div>{workout.exercises.map((e,i)=><div className="exercise" key={e.name}><div><i>{i+1}</i><span><button className="exercise-name" onClick={()=>setInfo(e)}>{e.name} ⓘ</button><small>Última vez: {last?.entries[e.name]?.weight||"—"} {e.unit}</small></span></div><strong>{e.sets} × {e.reps}</strong><label><input type="number" step="0.5" min="0" value={entries[e.name]?.weight||""} onChange={ev=>setEntries({...entries,[e.name]:{...entries[e.name],weight:ev.target.value}})}/><span>{e.unit}</span></label></div>)}</article><aside className="session-side"><Timer initial={data.settings.restSeconds}/><div><small>PRÓXIMO OBJETIVO</small><h3>Progresión sencilla</h3><p>Cuando completes el máximo de repeticiones con buena técnica, sube el mínimo peso disponible.</p></div><div><small>HISTORIAL</small><p><b>{data.sessions.filter(s=>s.workoutId===workoutId).length} sesiones</b> registradas</p>{last&&<p>Última: <b>{new Date(`${last.date}T12:00`).toLocaleDateString("es-ES")}</b></p>}</div></aside></div>{info&&<InfoModal exercise={info} close={()=>setInfo(null)}/>}</section>
}
function Timer({initial}:{initial:number}){const [seconds,setSeconds]=useState(initial);const [running,setRunning]=useState(false);const ref=useRef<number|undefined>(undefined);useEffect(()=>{if(running)ref.current=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);navigator.vibrate?.([200,100,200]);return 0}return s-1}),1000);return()=>window.clearInterval(ref.current)},[running]);const display=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;return <div className="timer"><small>DESCANSO</small><b>{display}</b><div className="timer-presets">{[60,90,120].map(x=><button key={x} onClick={()=>{setSeconds(x);setRunning(false)}}>{x}s</button>)}</div><button onClick={()=>setRunning(x=>!x)}>{running?"Pausar":"Iniciar"}</button><button onClick={()=>{setRunning(false);setSeconds(initial)}}>Reiniciar</button></div>}
function InfoModal({exercise,close}:{exercise:Exercise;close:()=>void}){useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==="Escape"&&close();window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[close]);return <div className="overlay" onMouseDown={close}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><small>TÉCNICA</small><h2>{exercise.name}</h2><p>{exercise.instructions}</p><p><b>Series:</b> {exercise.sets} · <b>Repeticiones:</b> {exercise.reps}</p></div></div>}

function Progress({data,update}:{data:AppData;update:(p:Partial<AppData>)=>void}){const [form,setForm]=useState(false);const [m,setM]=useState({date:localISO(),weight:"",fat:"",muscle:""});const sorted=[...data.measurements].sort((a,b)=>a.date.localeCompare(b.date));const latest=sorted[sorted.length-1];const first=sorted[0];const add=()=>{if(!m.weight)return;update({measurements:[...data.measurements,{id:uid(),date:m.date,weight:Number(m.weight),fat:m.fat?Number(m.fat):undefined,muscle:m.muscle?Number(m.muscle):undefined}]});setForm(false)};
 return <section className="page"><div className="title-row"><div><small>PROGRESO</small><h1>Mira la tendencia, no un solo día</h1><p>Registra la báscula siempre en condiciones parecidas.</p></div><button className="primary" onClick={()=>setForm(!form)}>+ Añadir medición</button></div>{form&&<div className="measurement-form"><label>Fecha<input type="date" value={m.date} onChange={e=>setM({...m,date:e.target.value})}/></label><label>Peso (kg)<input type="number" step="0.1" value={m.weight} onChange={e=>setM({...m,weight:e.target.value})}/></label><label>Grasa (%)<input type="number" step="0.1" value={m.fat} onChange={e=>setM({...m,fat:e.target.value})}/></label><label>Músculo (kg)<input type="number" step="0.1" value={m.muscle} onChange={e=>setM({...m,muscle:e.target.value})}/></label><button className="primary" onClick={add}>Guardar</button></div>} {latest?<><div className="progress-cards"><ProgressCard label="Peso" value={latest.weight} unit="kg" change={first?latest.weight-first.weight:0}/><ProgressCard label="Grasa corporal" value={latest.fat} unit="%" change={first&&latest.fat!=null&&first.fat!=null?latest.fat-first.fat:undefined}/><ProgressCard label="Masa muscular" value={latest.muscle} unit="kg" change={first&&latest.muscle!=null&&first.muscle!=null?latest.muscle-first.muscle:undefined}/></div><article className="chart-card"><div className="section-head"><h2>Evolución del peso</h2><span>{sorted.length} mediciones</span></div><Trend values={sorted.map(x=>x.weight)} labels={sorted.map(x=>new Date(`${x.date}T12:00`).toLocaleDateString("es-ES",{day:"numeric",month:"short"}))}/><div className="history-list">{[...sorted].reverse().map(x=><div key={x.id}><span>{new Date(`${x.date}T12:00`).toLocaleDateString("es-ES")}</span><b>{x.weight} kg</b><button onClick={()=>update({measurements:data.measurements.filter(y=>y.id!==x.id)})}>Eliminar</button></div>)}</div></article></>:<div className="empty-state"><h2>Aún no hay mediciones</h2><p>Añade la primera para empezar a ver una tendencia real.</p></div>}</section>}
function ProgressCard({label,value,unit,change}:{label:string;value?:number;unit:string;change?:number}){return <article><small>{label}</small><b>{value??"—"} <i>{value!=null?unit:""}</i></b><span>{change==null?"Sin comparación":`${change>0?"+":""}${change.toFixed(1)} ${unit} desde el inicio`}</span></article>}
function Trend({values,labels}:{values:number[];labels:string[]}){if(values.length<2)return <div className="chart one">Añade otra medición para ver la gráfica.</div>;const min=Math.min(...values)-.3,max=Math.max(...values)+.3;const pts=values.map((v,i)=>`${(i/(values.length-1))*100},${90-((v-min)/(max-min))*75}`).join(" ");return <div className="real-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/>{values.map((v,i)=><circle key={i} cx={(i/(values.length-1))*100} cy={90-((v-min)/(max-min))*75} r="1.4"/>)}</svg><div className="axis">{labels.map((x,i)=><span key={i}>{x}</span>)}</div></div>}

function SettingsPage({data,update,notify}:{data:AppData;update:(p:Partial<AppData>)=>void;notify:(s:string)=>void}){const s=data.settings;const file=useRef<HTMLInputElement>(null);const set=(p:Partial<Settings>)=>update({settings:{...s,...p}});const download=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`equilibra-copia-${localISO()}.json`;a.click();URL.revokeObjectURL(a.href)};const restore=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));setDataSafe(x,update);notify("Copia restaurada")}catch{notify("El archivo no es válido")}};r.readAsText(f)};
 return <section className="page"><div className="title-row"><div><small>AJUSTES</small><h1>Tu Equilibra</h1><p>Personaliza objetivos, presupuesto y apariencia.</p></div></div><div className="settings-grid"><article><h2>Perfil y objetivos diarios</h2><label>Nombre<input value={s.name} onChange={e=>set({name:e.target.value})}/></label><label>Calorías (kcal)<input type="number" min="1200" value={s.calorieGoal} onChange={e=>set({calorieGoal:Number(e.target.value)})}/></label><label>Proteína (g)<input type="number" min="1" value={s.proteinGoal} onChange={e=>set({proteinGoal:Number(e.target.value)})}/></label><label>Carbohidratos (g)<input type="number" min="1" value={s.carbGoal} onChange={e=>set({carbGoal:Number(e.target.value)})}/></label><label>Grasas (g)<input type="number" min="1" value={s.fatGoal} onChange={e=>set({fatGoal:Number(e.target.value)})}/></label><label>Presupuesto semanal (€)<input type="number" min="1" value={s.weeklyBudget} onChange={e=>set({weeklyBudget:Number(e.target.value)})}/></label><label>Presupuesto mensual (€)<input type="number" min="1" value={s.monthlyBudget} onChange={e=>set({monthlyBudget:Number(e.target.value)})}/></label><label>Descanso predeterminado (s)<input type="number" min="15" value={s.restSeconds} onChange={e=>set({restSeconds:Number(e.target.value)})}/></label></article><article><h2>Apariencia y datos</h2><label className="toggle"><input type="checkbox" checked={s.dark} onChange={e=>set({dark:e.target.checked})}/> Modo oscuro</label><p className="muted">Tus datos se guardan únicamente en este navegador. Crea una copia antes de borrar datos o cambiar de dispositivo.</p><button className="secondary" onClick={download}>Descargar copia de seguridad</button><button className="secondary" onClick={()=>file.current?.click()}>Restaurar copia</button><input ref={file} hidden type="file" accept="application/json" onChange={e=>restore(e.target.files?.[0])}/></article></div></section>}
function setDataSafe(x:Partial<AppData>,update:(p:Partial<AppData>)=>void){if(!x||typeof x!=="object"||!Array.isArray(x.sessions)||!x.settings)throw new Error();update({...defaults,...x,settings:{...defaults.settings,...x.settings}})}
