import React, { useEffect, useMemo, useRef, useState } from "react";

type View = "hoy" | "plan" | "compra" | "entreno" | "progreso" | "ajustes";
type Meal = { id:string; type:string; name:string; kcal:number; protein:number; prep:string; ingredients:{name:string;qty:number;unit:string;price:number}[] };
type Exercise = { name:string; sets:number; reps:string; unit:string; defaultWeight:number; instructions:string };
type Workout = { id:string; name:string; kind:"pump"|"strength"|"rest"; duration:number; exercises:Exercise[] };
type Session = { id:string; date:string; workoutId:string; entries:Record<string,{weight:string;reps:string}>; completed:boolean };
type Measurement = { id:string; date:string; weight:number; fat?:number; muscle?:number };
type Settings = { name:string; weeklyBudget:number; monthlyBudget:number; proteinGoal:number; restSeconds:number; dark:boolean };
type AppData = { mealChoices:Record<string,string>; freeMeals:string[]; unavailable:string[]; scheduleOverrides:Record<string,string>; shoppingChecked:string[]; extraItems:string[]; sessions:Session[]; measurements:Measurement[]; settings:Settings; streakDates:string[] };

const mealOptions:Record<string,Meal[]> = {
 breakfast:[
  {id:"breakfast-toast",type:"Desayuno",name:"Tostada con tomate, cottage y pavo",kcal:365,protein:27,prep:"Tuesta el pan, añade tomate, cottage y pavo. Acompaña con café y leche.",ingredients:[{name:"Pan integral",qty:70,unit:"g",price:.32},{name:"Tomate",qty:100,unit:"g",price:.28},{name:"Queso cottage",qty:80,unit:"g",price:.72},{name:"Pavo loncheado",qty:50,unit:"g",price:.85},{name:"Leche semidesnatada",qty:150,unit:"ml",price:.16},{name:"Café",qty:1,unit:"taza",price:.18}]},
  {id:"breakfast-yogurt",type:"Desayuno",name:"Bol de yogur, avena y fruta",kcal:390,protein:25,prep:"Mezcla el yogur con avena y fruta. Añade canela al gusto.",ingredients:[{name:"Yogur griego natural",qty:250,unit:"g",price:1.1},{name:"Copos de avena",qty:45,unit:"g",price:.12},{name:"Plátano",qty:1,unit:"ud",price:.32},{name:"Almendras",qty:10,unit:"g",price:.2}]}
 ],
 lunch:[
  {id:"lunch-chicken",type:"Comida",name:"Pollo mediterráneo con arroz",kcal:585,protein:45,prep:"Cuece el arroz. Saltea pollo y verduras con el aceite medido y mezcla.",ingredients:[{name:"Pechuga de pollo",qty:150,unit:"g",price:1.35},{name:"Arroz",qty:70,unit:"g",price:.16},{name:"Calabacín",qty:120,unit:"g",price:.24},{name:"Pimiento rojo",qty:80,unit:"g",price:.25},{name:"Aceite de oliva",qty:10,unit:"ml",price:.09}]},
  {id:"lunch-lentils",type:"Comida",name:"Ensalada templada de lentejas y huevo",kcal:560,protein:32,prep:"Mezcla las lentejas escurridas con verduras salteadas y huevo cocido.",ingredients:[{name:"Lentejas cocidas",qty:250,unit:"g",price:.85},{name:"Huevos",qty:2,unit:"ud",price:.5},{name:"Tomate",qty:120,unit:"g",price:.34},{name:"Espinacas",qty:80,unit:"g",price:.6},{name:"Aceite de oliva",qty:10,unit:"ml",price:.09}]},
  {id:"lunch-salmon",type:"Comida",name:"Salmón con patata y ensalada",kcal:610,protein:39,prep:"Hornea el salmón y la patata. Sirve con ensalada y limón.",ingredients:[{name:"Salmón",qty:150,unit:"g",price:2.8},{name:"Patatas",qty:250,unit:"g",price:.38},{name:"Mezcla de ensalada",qty:100,unit:"g",price:.75},{name:"Aceite de oliva",qty:8,unit:"ml",price:.08}]}
 ],
 dinner:[
  {id:"dinner-omelette",type:"Cena",name:"Crema de calabacín y tortilla",kcal:430,protein:28,prep:"Cuece y tritura la crema. Prepara la tortilla con huevos y claras.",ingredients:[{name:"Calabacín",qty:300,unit:"g",price:.6},{name:"Patatas",qty:100,unit:"g",price:.15},{name:"Cebolla",qty:60,unit:"g",price:.1},{name:"Huevos",qty:2,unit:"ud",price:.5},{name:"Claras",qty:100,unit:"ml",price:.55},{name:"Aceite de oliva",qty:5,unit:"ml",price:.05}]},
  {id:"dinner-wrap",type:"Cena",name:"Wrap integral de pollo y verduras",kcal:455,protein:35,prep:"Saltea el pollo y las verduras. Rellena y tuesta el wrap.",ingredients:[{name:"Tortilla integral",qty:1,unit:"ud",price:.35},{name:"Pechuga de pollo",qty:110,unit:"g",price:.99},{name:"Pimiento rojo",qty:60,unit:"g",price:.19},{name:"Cebolla",qty:40,unit:"g",price:.07},{name:"Yogur natural",qty:50,unit:"g",price:.18}]},
  {id:"dinner-hake",type:"Cena",name:"Merluza con verduras al horno",kcal:420,protein:38,prep:"Hornea la merluza y las verduras 20 minutos con limón y especias.",ingredients:[{name:"Merluza",qty:180,unit:"g",price:2.1},{name:"Calabacín",qty:180,unit:"g",price:.36},{name:"Tomate",qty:120,unit:"g",price:.34},{name:"Patatas",qty:150,unit:"g",price:.23},{name:"Aceite de oliva",qty:8,unit:"ml",price:.08}]}
 ]
};

const strengthA:Exercise[]=[
 {name:"Sentadilla en multipower",sets:3,reps:"8–10",unit:"kg",defaultWeight:30,instructions:"Pies algo adelantados, rodillas en línea con los pies y espalda neutra. Baja sin dolor y empuja el suelo."},
 {name:"Peso muerto rumano",sets:3,reps:"10",unit:"kg",defaultWeight:22,instructions:"Lleva la cadera atrás con rodillas suaves. Mantén la carga cerca del cuerpo y la espalda neutra."},
 {name:"Remo sentado",sets:3,reps:"10–12",unit:"kg",defaultWeight:25,instructions:"Pecho estable, hombros lejos de las orejas. Lleva los codos atrás sin balancearte."},
 {name:"Press de pecho",sets:3,reps:"8–10",unit:"kg",defaultWeight:17.5,instructions:"Escápulas apoyadas y muñecas neutras. Baja con control y no bloquees los codos."},
 {name:"Hip thrust",sets:3,reps:"10",unit:"kg",defaultWeight:40,instructions:"Barbilla recogida, pelvis neutra y pausa arriba apretando glúteos sin arquear la espalda."}
];
const strengthB:Exercise[]=[
 {name:"Prensa inclinada",sets:3,reps:"10–12",unit:"kg",defaultWeight:55,instructions:"Apoya toda la espalda y coloca los pies a una anchura cómoda. No bloquees las rodillas."},
 {name:"Jalón al pecho",sets:3,reps:"10–12",unit:"kg",defaultWeight:25,instructions:"Baja la barra hacia la parte alta del pecho llevando los codos abajo, sin tirar con impulso."},
 {name:"Zancada atrás",sets:3,reps:"8 por lado",unit:"kg",defaultWeight:8,instructions:"Da un paso atrás y mantén estable la rodilla delantera. Empuja con el pie delantero."},
 {name:"Press de hombro",sets:3,reps:"10",unit:"kg",defaultWeight:10,instructions:"Costillas controladas y hombros bajos. Empuja arriba sin arquear la zona lumbar."},
 {name:"Plancha",sets:3,reps:"30–45 s",unit:"s",defaultWeight:30,instructions:"Contrae abdomen y glúteos manteniendo una línea recta. Para si pierdes la postura."}
];
const workouts:Record<string,Workout>={pump:{id:"pump",name:"BodyPump",kind:"pump",duration:60,exercises:[]},strengthA:{id:"strengthA",name:"Fuerza A",kind:"strength",duration:50,exercises:strengthA},strengthB:{id:"strengthB",name:"Fuerza B",kind:"strength",duration:45,exercises:strengthB},rest:{id:"rest",name:"Descanso activo",kind:"rest",duration:20,exercises:[]}};
const schedule=["pump","rest","strengthA","rest","pump","strengthB","rest"];
const defaults:AppData={mealChoices:{breakfast:"breakfast-toast",lunch:"lunch-chicken",dinner:"dinner-omelette"},freeMeals:[],unavailable:[],scheduleOverrides:{},shoppingChecked:[],extraItems:[],sessions:[],measurements:[],settings:{name:"",weeklyBudget:35,monthlyBudget:100,proteinGoal:105,restSeconds:90,dark:false},streakDates:[]};
const iso=(d:Date)=>d.toISOString().slice(0,10);
const localISO=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return iso(x)};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const money=(n:number)=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"});
function load():AppData {try{const raw=JSON.parse(localStorage.getItem("equilibra-v2")||"null");return raw?{...defaults,...raw,settings:{...defaults.settings,...raw.settings}}:defaults}catch{return defaults}}

const Icon=({name}:{name:string})=>{const p:Record<string,string>={hoy:"M3 11.5 12 4l9 7.5M5.5 10v10h13V10M9 20v-6h6v6",plan:"M6 3v3m12-3v3M4 8h16v12H4z",compra:"M4 6h16l-2 14H6L4 6z",entreno:"M3 9v6m3-8v10m3-6h6m0-4v10m3-8v6",progreso:"M4 18l5-5 4 3 7-9m-5 0h5v5",ajustes:"M12 8a4 4 0 100 8 4 4 0 000-8zm0-5v2m0 14v2M3 12h2m14 0h2"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={p[name]}/></svg>};

export default function App(){
 const [data,setData]=useState<AppData>(load); const [view,setView]=useState<View>("hoy"); const [modal,setModal]=useState<Meal|null>(null); const [toast,setToast]=useState("");
 useEffect(()=>{localStorage.setItem("equilibra-v2",JSON.stringify(data));document.documentElement.dataset.theme=data.settings.dark?"dark":"light"},[data]);
 const update=(patch:Partial<AppData>)=>setData(d=>({...d,...patch})); const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2200)};
 const chosen=useMemo(()=>Object.entries(data.mealChoices).map(([slot,id])=>mealOptions[slot].find(m=>m.id===id)!).filter(Boolean),[data.mealChoices]);
 const activeMeals=chosen.filter(m=>!data.freeMeals.includes(m.id)); const protein=activeMeals.reduce((n,m)=>n+m.protein,0); const kcal=activeMeals.reduce((n,m)=>n+m.kcal,0);
 const now=new Date(); const hour=now.getHours(); const greeting=hour<13?"Buenos días":hour<20?"Buenas tardes":"Buenas noches";
 const dateText=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long"}).format(now);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><span className="sprig">⌁</span>Equilibra</div><nav>{(["hoy","plan","compra","entreno","progreso","ajustes"] as View[]).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?"active":""}><Icon name={v}/><span>{v[0].toUpperCase()+v.slice(1)}</span></button>)}</nav><div className="side-note"><b>Este mes</b><span>{data.sessions.filter(s=>s.completed&&s.date.slice(0,7)===localISO().slice(0,7)).length} entrenamientos completados</span></div></aside>
  <main className="content"><header><div><p>{greeting}{data.settings.name?`, ${data.settings.name}`:""}</p><span>{dateText[0].toUpperCase()+dateText.slice(1)}</span></div><button className="avatar" onClick={()=>setView("ajustes")} aria-label="Abrir ajustes">{data.settings.name.slice(0,2).toUpperCase()||"EQ"}</button></header>
   {view==="hoy"&&<Today data={data} meals={chosen} kcal={kcal} protein={protein} setModal={setModal} update={update} goWorkout={()=>setView("entreno")}/>}
   {view==="plan"&&<Plan data={data} update={update} meals={chosen} setModal={setModal}/>}
   {view==="compra"&&<Shopping data={data} meals={activeMeals} update={update}/>}
   {view==="entreno"&&<Training data={data} update={update} notify={notify}/>}
   {view==="progreso"&&<Progress data={data} update={update}/>}
   {view==="ajustes"&&<SettingsPage data={data} update={update} notify={notify}/>}
  </main>{modal&&<MealModal meal={modal} data={data} update={update} close={()=>setModal(null)}/>} {toast&&<div className="toast" role="status">{toast}</div>}
 </div>
}

function Today({data,meals,kcal,protein,setModal,update,goWorkout}:{data:AppData;meals:Meal[];kcal:number;protein:number;setModal:(m:Meal)=>void;update:(p:Partial<AppData>)=>void;goWorkout:()=>void}){
 const today=localISO(),dow=(new Date().getDay()+6)%7; const workout=workouts[schedule[dow]]; const done=data.sessions.some(s=>s.date===today&&s.completed);
 const toggleFree=(id:string)=>update({freeMeals:data.freeMeals.includes(id)?data.freeMeals.filter(x=>x!==id):[...data.freeMeals,id]});
 return <section className="page"><div className="title-row"><div><small>HOY</small><h1>Tu día, en equilibrio</h1><p>Un plan realista que se adapta a ti.</p></div><div className="streak">✦ <b>{data.streakDates.length} días</b><span>registrados en tu plan</span></div></div><div className="today-grid"><div className="meal-stack"><div className="section-head"><h2>Comidas</h2><span>{kcal} kcal previstas</span></div>{meals.map((m,i)=><article className={`meal-card ${data.freeMeals.includes(m.id)?"free":""}`} key={m.id}><div className={`meal-art art-${i}`}>{["☕","◒","♨"][i]}</div><div className="meal-copy"><small>{m.type}</small><h3>{data.freeMeals.includes(m.id)?"Comida libre":m.name}</h3><span>{data.freeMeals.includes(m.id)?"No se añadirá a la compra":`${m.kcal} kcal · ${m.protein} g proteína`}</span></div><div className="meal-actions"><button onClick={()=>setModal(m)}>Ver receta</button><button className="dots" onClick={()=>toggleFree(m.id)} aria-label={data.freeMeals.includes(m.id)?"Volver a incluir":"Marcar como libre"}>{data.freeMeals.includes(m.id)?"↩":"•••"}</button></div></article>)}</div><div className="right-col"><article className="workout-card"><div><small>ENTRENAMIENTO DE HOY</small><h2>{workout.name}</h2><p>{workout.duration} min · {done?"Completado":"Pendiente"}</p><button onClick={goWorkout}>{done?"Ver historial":"Abrir entrenamiento"} →</button></div><div className="barbell">●━●</div></article><div className="metric-row"><Metric label="Proteína" value={`${protein}`} total={`${data.settings.proteinGoal} g`} pct={protein/data.settings.proteinGoal*100}/><Metric label="Presupuesto" value={money(estimate(meals))} total={money(data.settings.weeklyBudget)} pct={estimate(meals)/data.settings.weeklyBudget*100}/></div><article className="tip"><span>Consejo del día</span><p>La constancia cuenta más que un día perfecto. Puedes ajustar el plan sin perder el rumbo.</p></article></div></div></section>
}
function Metric({label,value,total,pct}:{label:string;value:string;total:string;pct:number}){return <article className="metric"><small>{label}</small><div className="ring" style={{"--pct":`${Math.min(100,pct)*3.6}deg`} as React.CSSProperties}><span>{value}<i>/ {total}</i></span></div></article>}
function getWeek(offset=0){const d=new Date();const diff=(d.getDay()+6)%7;d.setDate(d.getDate()-diff+offset*7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x})}

function Plan({data,update,meals,setModal}:{data:AppData;update:(p:Partial<AppData>)=>void;meals:Meal[];setModal:(m:Meal)=>void}){
 const [weekOffset,setWeekOffset]=useState(0);const days=getWeek(weekOffset);const [changing,setChanging]=useState<string|null>(null);
 return <section className="page"><div className="title-row"><div><small>PLAN SEMANAL</small><h1>Tu semana</h1><p>Marca indisponibilidad o mueve cualquier sesión desde el selector.</p></div><div className="week-nav"><button onClick={()=>setWeekOffset(x=>x-1)}>←</button><button onClick={()=>setWeekOffset(0)}>Hoy</button><button onClick={()=>setWeekOffset(x=>x+1)}>→</button></div></div><div className="week-grid">{days.map((d,i)=>{const key=localISO(d),blocked=data.unavailable.includes(key);const workout=workouts[blocked?"rest":(data.scheduleOverrides[key]||schedule[i])];return <article className={`day-card ${key===localISO()?"today":""} ${blocked?"blocked":""}`} key={key}><div><b>{new Intl.DateTimeFormat("es-ES",{weekday:"short"}).format(d)}</b><span>{d.getDate()}</span></div><i className={workout.kind}/><select className="day-workout" value={data.scheduleOverrides[key]||schedule[i]} disabled={blocked} onChange={e=>update({scheduleOverrides:{...data.scheduleOverrides,[key]:e.target.value}})}><option value="pump">BodyPump</option><option value="strengthA">Fuerza A</option><option value="strengthB">Fuerza B</option><option value="rest">Descanso activo</option></select><p>{workout.duration} min</p><label className="available"><input type="checkbox" checked={blocked} onChange={()=>update({unavailable:blocked?data.unavailable.filter(x=>x!==key):[...data.unavailable,key]})}/> No disponible</label>{key===localISO()&&<em>Hoy</em>}</article>})}</div><div className="replan"><b>Plan flexible</b><span>Al marcar un día como no disponible se convierte en descanso. Usa los selectores para mover la sesión al siguiente hueco, dejando 24 horas entre entrenamientos intensos.</span></div><div className="plan-bottom"><article><div className="section-head"><h2>Entrenamiento</h2><span>Objetivo: 3–4 días</span></div><ul className="logic-list"><li><b>Prioridad</b><span>Fuerza A y dos clases BodyPump; Fuerza B queda opcional.</span></li><li><b>Recuperación</b><span>Deja al menos 24 horas entre sesiones intensas y evita compensar con cardio extra.</span></li></ul></article><article><div className="section-head"><h2>Menú de hoy</h2><span>{money(estimate(meals))}</span></div>{meals.map(m=><div key={m.id} className="mini-wrap"><button className="mini-meal" onClick={()=>setModal(m)}><span>{m.type}</span><b>{m.name}</b><em>Ver receta →</em></button><button className="swap" onClick={()=>setChanging(changing===m.type?null:m.type)}>Cambiar</button>{changing===m.type&&<MealPicker slot={Object.keys(mealOptions).find(k=>mealOptions[k].some(x=>x.type===m.type))!} data={data} update={update} close={()=>setChanging(null)}/>}</div>)}</article></div></section>
}
function MealPicker({slot,data,update,close}:{slot:string;data:AppData;update:(p:Partial<AppData>)=>void;close:()=>void}){return <div className="picker">{mealOptions[slot].map(m=><button key={m.id} onClick={()=>{update({mealChoices:{...data.mealChoices,[slot]:m.id},freeMeals:data.freeMeals.filter(x=>!mealOptions[slot].some(y=>y.id===x))});close()}}><b>{m.name}</b><span>{m.kcal} kcal · {m.protein} g proteína · {money(estimate([m]))}</span></button>)}</div>}
function estimate(meals:Meal[]){return meals.reduce((n,m)=>n+m.ingredients.reduce((s,x)=>s+x.price,0),0)*7}
function Shopping({data,meals,update}:{data:AppData;meals:Meal[];update:(p:Partial<AppData>)=>void}){
 const [extra,setExtra]=useState("");const items=useMemo(()=>{const map=new Map<string,{qty:number;unit:string;price:number}>();meals.flatMap(m=>m.ingredients).forEach(x=>{const old=map.get(x.name);map.set(x.name,{qty:(old?.qty||0)+x.qty,unit:x.unit,price:(old?.price||0)+x.price})});return [...map].map(([name,x])=>({name,...x,qty:x.qty*7,price:x.price*7}))},[meals]);const total=items.reduce((n,x)=>n+x.price,0);
 const toggle=(name:string)=>update({shoppingChecked:data.shoppingChecked.includes(name)?data.shoppingChecked.filter(x=>x!==name):[...data.shoppingChecked,name]});
 return <section className="page"><div className="title-row"><div><small>COMPRA SEMANAL</small><h1>Lo necesario, sin desperdiciar</h1><p>Se recalcula cuando cambias o marcas una comida como libre.</p></div><div className="budget-pill"><b>{money(total)}</b><span>de {money(data.settings.weeklyBudget)}</span></div></div>{total>data.settings.weeklyBudget&&<div className="warning"><b>Presupuesto superado</b><span>Elige una alternativa más económica o ajusta el límite en Ajustes.</span></div>}<div className="shopping-toolbar"><button onClick={()=>update({shoppingChecked:items.map(x=>x.name)})}>Marcar todo</button><button onClick={()=>update({shoppingChecked:[]})}>Reiniciar</button><label><input type="text" value={extra} placeholder="Añadir producto" onChange={e=>setExtra(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&extra.trim()){update({extraItems:[...data.extraItems,extra.trim()]});setExtra("")}}}/><button onClick={()=>{if(extra.trim()){update({extraItems:[...data.extraItems,extra.trim()]});setExtra("")}}}>Añadir</button></label></div><div className="shopping-grid dynamic"><article><h2>Menú</h2>{items.map(x=><label key={x.name}><input type="checkbox" checked={data.shoppingChecked.includes(x.name)} onChange={()=>toggle(x.name)}/><span>{x.name} · {Number.isInteger(x.qty)?x.qty:x.qty.toFixed(0)} {x.unit}</span><em>{money(x.price)}</em></label>)}</article><article><h2>Extras</h2>{data.extraItems.length===0&&<p className="empty">No has añadido extras.</p>}{data.extraItems.map(x=><label key={x}><input type="checkbox" checked={data.shoppingChecked.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span><button className="remove" onClick={()=>update({extraItems:data.extraItems.filter(y=>y!==x),shoppingChecked:data.shoppingChecked.filter(y=>y!==x)})}>×</button></label>)}</article></div></section>
}

function Training({data,update,notify}:{data:AppData;update:(p:Partial<AppData>)=>void;notify:(s:string)=>void}){
 const [workoutId,setWorkoutId]=useState("strengthA");const workout=workouts[workoutId];const last=[...data.sessions].reverse().find(s=>s.workoutId===workoutId&&s.completed);const [entries,setEntries]=useState<Record<string,{weight:string;reps:string}>>({});const [info,setInfo]=useState<Exercise|null>(null);
 useEffect(()=>setEntries(Object.fromEntries(workout.exercises.map(e=>[e.name,{weight:last?.entries[e.name]?.weight||String(e.defaultWeight),reps:last?.entries[e.name]?.reps||e.reps}]))),[workoutId]);
 const save=()=>{const session:Session={id:uid(),date:localISO(),workoutId,entries,completed:true};const dates=[...new Set([...data.streakDates,localISO()])];update({sessions:[...data.sessions,session],streakDates:dates});notify("Sesión guardada correctamente")};
 return <section className="page"><div className="title-row"><div><small>ENTRENAMIENTO</small><h1>{workout.name}</h1><p>{workout.duration} minutos · tu última sesión siempre visible.</p></div><div className="workout-actions"><select value={workoutId} onChange={e=>setWorkoutId(e.target.value)}><option value="strengthA">Fuerza A</option><option value="strengthB">Fuerza B</option></select><button className="primary" onClick={save}>Finalizar y guardar</button></div></div><div className="workout-layout"><article className="exercise-list"><div className="table-head"><span>Ejercicio</span><span>Series × repeticiones</span><span>Peso de hoy</span></div>{workout.exercises.map((e,i)=><div className="exercise" key={e.name}><div><i>{i+1}</i><span><button className="exercise-name" onClick={()=>setInfo(e)}>{e.name} ⓘ</button><small>Última vez: {last?.entries[e.name]?.weight||"—"} {e.unit}</small></span></div><strong>{e.sets} × {e.reps}</strong><label><input type="number" step="0.5" min="0" value={entries[e.name]?.weight||""} onChange={ev=>setEntries({...entries,[e.name]:{...entries[e.name],weight:ev.target.value}})}/><span>{e.unit}</span></label></div>)}</article><aside className="session-side"><Timer initial={data.settings.restSeconds}/><div><small>PRÓXIMO OBJETIVO</small><h3>Progresión sencilla</h3><p>Cuando completes el máximo de repeticiones con buena técnica, sube el mínimo peso disponible.</p></div><div><small>HISTORIAL</small><p><b>{data.sessions.filter(s=>s.workoutId===workoutId).length} sesiones</b> registradas</p>{last&&<p>Última: <b>{new Date(`${last.date}T12:00`).toLocaleDateString("es-ES")}</b></p>}</div></aside></div>{info&&<InfoModal exercise={info} close={()=>setInfo(null)}/>}</section>
}
function Timer({initial}:{initial:number}){const [seconds,setSeconds]=useState(initial);const [running,setRunning]=useState(false);const ref=useRef<number|undefined>(undefined);useEffect(()=>{if(running)ref.current=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);navigator.vibrate?.([200,100,200]);return 0}return s-1}),1000);return()=>window.clearInterval(ref.current)},[running]);const display=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;return <div className="timer"><small>DESCANSO</small><b>{display}</b><div className="timer-presets">{[60,90,120].map(x=><button key={x} onClick={()=>{setSeconds(x);setRunning(false)}}>{x}s</button>)}</div><button onClick={()=>setRunning(x=>!x)}>{running?"Pausar":"Iniciar"}</button><button onClick={()=>{setRunning(false);setSeconds(initial)}}>Reiniciar</button></div>}
function InfoModal({exercise,close}:{exercise:Exercise;close:()=>void}){useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==="Escape"&&close();window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[close]);return <div className="overlay" onMouseDown={close}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><small>TÉCNICA</small><h2>{exercise.name}</h2><p>{exercise.instructions}</p><p><b>Series:</b> {exercise.sets} · <b>Repeticiones:</b> {exercise.reps}</p></div></div>}

function Progress({data,update}:{data:AppData;update:(p:Partial<AppData>)=>void}){const [form,setForm]=useState(false);const [m,setM]=useState({date:localISO(),weight:"",fat:"",muscle:""});const sorted=[...data.measurements].sort((a,b)=>a.date.localeCompare(b.date));const latest=sorted[sorted.length-1];const first=sorted[0];const add=()=>{if(!m.weight)return;update({measurements:[...data.measurements,{id:uid(),date:m.date,weight:Number(m.weight),fat:m.fat?Number(m.fat):undefined,muscle:m.muscle?Number(m.muscle):undefined}]});setForm(false)};
 return <section className="page"><div className="title-row"><div><small>PROGRESO</small><h1>Mira la tendencia, no un solo día</h1><p>Registra la báscula siempre en condiciones parecidas.</p></div><button className="primary" onClick={()=>setForm(!form)}>+ Añadir medición</button></div>{form&&<div className="measurement-form"><label>Fecha<input type="date" value={m.date} onChange={e=>setM({...m,date:e.target.value})}/></label><label>Peso (kg)<input type="number" step="0.1" value={m.weight} onChange={e=>setM({...m,weight:e.target.value})}/></label><label>Grasa (%)<input type="number" step="0.1" value={m.fat} onChange={e=>setM({...m,fat:e.target.value})}/></label><label>Músculo (kg)<input type="number" step="0.1" value={m.muscle} onChange={e=>setM({...m,muscle:e.target.value})}/></label><button className="primary" onClick={add}>Guardar</button></div>} {latest?<><div className="progress-cards"><ProgressCard label="Peso" value={latest.weight} unit="kg" change={first?latest.weight-first.weight:0}/><ProgressCard label="Grasa corporal" value={latest.fat} unit="%" change={first&&latest.fat!=null&&first.fat!=null?latest.fat-first.fat:undefined}/><ProgressCard label="Masa muscular" value={latest.muscle} unit="kg" change={first&&latest.muscle!=null&&first.muscle!=null?latest.muscle-first.muscle:undefined}/></div><article className="chart-card"><div className="section-head"><h2>Evolución del peso</h2><span>{sorted.length} mediciones</span></div><Trend values={sorted.map(x=>x.weight)} labels={sorted.map(x=>new Date(`${x.date}T12:00`).toLocaleDateString("es-ES",{day:"numeric",month:"short"}))}/><div className="history-list">{[...sorted].reverse().map(x=><div key={x.id}><span>{new Date(`${x.date}T12:00`).toLocaleDateString("es-ES")}</span><b>{x.weight} kg</b><button onClick={()=>update({measurements:data.measurements.filter(y=>y.id!==x.id)})}>Eliminar</button></div>)}</div></article></>:<div className="empty-state"><h2>Aún no hay mediciones</h2><p>Añade la primera para empezar a ver una tendencia real.</p></div>}</section>}
function ProgressCard({label,value,unit,change}:{label:string;value?:number;unit:string;change?:number}){return <article><small>{label}</small><b>{value??"—"} <i>{value!=null?unit:""}</i></b><span>{change==null?"Sin comparación":`${change>0?"+":""}${change.toFixed(1)} ${unit} desde el inicio`}</span></article>}
function Trend({values,labels}:{values:number[];labels:string[]}){if(values.length<2)return <div className="chart one">Añade otra medición para ver la gráfica.</div>;const min=Math.min(...values)-.3,max=Math.max(...values)+.3;const pts=values.map((v,i)=>`${(i/(values.length-1))*100},${90-((v-min)/(max-min))*75}`).join(" ");return <div className="real-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts}/>{values.map((v,i)=><circle key={i} cx={(i/(values.length-1))*100} cy={90-((v-min)/(max-min))*75} r="1.4"/>)}</svg><div className="axis">{labels.map((x,i)=><span key={i}>{x}</span>)}</div></div>}

function SettingsPage({data,update,notify}:{data:AppData;update:(p:Partial<AppData>)=>void;notify:(s:string)=>void}){const s=data.settings;const file=useRef<HTMLInputElement>(null);const set=(p:Partial<Settings>)=>update({settings:{...s,...p}});const download=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`equilibra-copia-${localISO()}.json`;a.click();URL.revokeObjectURL(a.href)};const restore=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));setDataSafe(x,update);notify("Copia restaurada")}catch{notify("El archivo no es válido")}};r.readAsText(f)};
 return <section className="page"><div className="title-row"><div><small>AJUSTES</small><h1>Tu Equilibra</h1><p>Personaliza objetivos, presupuesto y apariencia.</p></div></div><div className="settings-grid"><article><h2>Perfil y objetivos</h2><label>Nombre<input value={s.name} onChange={e=>set({name:e.target.value})}/></label><label>Objetivo de proteína (g)<input type="number" min="1" value={s.proteinGoal} onChange={e=>set({proteinGoal:Number(e.target.value)})}/></label><label>Presupuesto semanal (€)<input type="number" min="1" value={s.weeklyBudget} onChange={e=>set({weeklyBudget:Number(e.target.value)})}/></label><label>Presupuesto mensual (€)<input type="number" min="1" value={s.monthlyBudget} onChange={e=>set({monthlyBudget:Number(e.target.value)})}/></label><label>Descanso predeterminado (s)<input type="number" min="15" value={s.restSeconds} onChange={e=>set({restSeconds:Number(e.target.value)})}/></label></article><article><h2>Apariencia y datos</h2><label className="toggle"><input type="checkbox" checked={s.dark} onChange={e=>set({dark:e.target.checked})}/> Modo oscuro</label><p className="muted">Tus datos se guardan únicamente en este navegador. Crea una copia antes de borrar datos o cambiar de dispositivo.</p><button className="secondary" onClick={download}>Descargar copia de seguridad</button><button className="secondary" onClick={()=>file.current?.click()}>Restaurar copia</button><input ref={file} hidden type="file" accept="application/json" onChange={e=>restore(e.target.files?.[0])}/></article></div></section>}
function setDataSafe(x:Partial<AppData>,update:(p:Partial<AppData>)=>void){if(!x||typeof x!=="object"||!Array.isArray(x.sessions)||!x.settings)throw new Error();update({...defaults,...x,settings:{...defaults.settings,...x.settings}})}
function MealModal({meal,data,update,close}:{meal:Meal;data:AppData;update:(p:Partial<AppData>)=>void;close:()=>void}){const slot=Object.keys(mealOptions).find(k=>mealOptions[k].some(x=>x.id===meal.id))!;useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==="Escape"&&close();window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[close]);const free=data.freeMeals.includes(meal.id);return <div className="overlay" onMouseDown={close}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="meal-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close} aria-label="Cerrar">×</button><small>{meal.type.toUpperCase()}</small><h2 id="meal-title">{meal.name}</h2><div className="macro-strip"><span><b>{meal.kcal}</b> kcal</span><span><b>{meal.protein}</b> g proteína</span></div><h3>Ingredientes para 1 ración</h3><ul>{meal.ingredients.map(x=><li key={x.name}>{x.name} — {x.qty} {x.unit}</li>)}</ul><h3>Preparación</h3><p>{meal.prep}</p><h3>Cambiar esta comida</h3><MealPicker slot={slot} data={data} update={update} close={close}/><div className="modal-actions"><button className="primary" onClick={()=>{update({freeMeals:free?data.freeMeals.filter(x=>x!==meal.id):[...data.freeMeals,meal.id]});close()}}>{free?"Volver a incluir":"Marcar como comida libre"}</button></div></div></div>}
